@startuml

class Index_html {
  - width: int
  - height: int
  - mycanvas: canvas
}



package "bundle" #DDDDDD{

class Main_js {
  constGame
  let my Game
  myGame.start()          
}


class Game {
  + gameConstants
  + gameState
  + gameHelpers
  - levels: int[]
  - current_level: int 
  + mainmenu()
  + start()
  + update()
  + end()
  + pause()
  + updateFrames()
  + tick()

}


class Player {
  - keydown_left: boolean
  - keydown_right: boolean
  - keydown_jump: boolean
  - Eventlistener_left
  - Eventlistener_right
  - Eventlistener_jump
  + startedPressingJump
  + stoppedPressingJump
  + applyGravity()
  + move()
}

class elementList {
  + add(element)
  + get(i)
  + delete(i)
  + draw(ctx)
  + action()
  + checkCollision(element)
}

class element {
  - positionX: int 
  - positionY: int 
  - width: int
  - height: int
  + draw()
  + checkCollision(element)
}


class Platform {
  - type: String
}



Game --> elementList
elementList --> element
Player -|>element
Platform -|> element
Main_js --> Game
}
Index_html -->bundle
@enduml